# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# Requires GitHub Sponsors on your account:
# https://github.com/sponsors/devyanshyadav

github: [devyanshyadav]
